// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: service.proto

package v1alpha

import (
	context "context"
	fmt "fmt"
	math "math"

	api "github.com/deps-cloud/des/api"
	schema "github.com/deps-cloud/dts/api/v1alpha/schema"

	proto "github.com/gogo/protobuf/proto"

	_ "google.golang.org/genproto/googleapis/api/annotations"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SourceRequest struct {
	Source               *schema.Source                  `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	ManagementFiles      []*api.DependencyManagementFile `protobuf:"bytes,2,rep,name=managementFiles,proto3" json:"managementFiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *SourceRequest) Reset()         { *m = SourceRequest{} }
func (m *SourceRequest) String() string { return proto.CompactTextString(m) }
func (*SourceRequest) ProtoMessage()    {}
func (*SourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}
func (m *SourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceRequest.Unmarshal(m, b)
}
func (m *SourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceRequest.Marshal(b, m, deterministic)
}
func (m *SourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceRequest.Merge(m, src)
}
func (m *SourceRequest) XXX_Size() int {
	return xxx_messageInfo_SourceRequest.Size(m)
}
func (m *SourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SourceRequest proto.InternalMessageInfo

func (m *SourceRequest) GetSource() *schema.Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *SourceRequest) GetManagementFiles() []*api.DependencyManagementFile {
	if m != nil {
		return m.ManagementFiles
	}
	return nil
}

type ListRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type TrackResponse struct {
	Tracking             bool     `protobuf:"varint,1,opt,name=tracking,proto3" json:"tracking,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackResponse) Reset()         { *m = TrackResponse{} }
func (m *TrackResponse) String() string { return proto.CompactTextString(m) }
func (*TrackResponse) ProtoMessage()    {}
func (*TrackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}
func (m *TrackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackResponse.Unmarshal(m, b)
}
func (m *TrackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackResponse.Marshal(b, m, deterministic)
}
func (m *TrackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackResponse.Merge(m, src)
}
func (m *TrackResponse) XXX_Size() int {
	return xxx_messageInfo_TrackResponse.Size(m)
}
func (m *TrackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrackResponse proto.InternalMessageInfo

func (m *TrackResponse) GetTracking() bool {
	if m != nil {
		return m.Tracking
	}
	return false
}

type ListSourceResponse struct {
	Page                 int32            `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count                int32            `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Sources              []*schema.Source `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListSourceResponse) Reset()         { *m = ListSourceResponse{} }
func (m *ListSourceResponse) String() string { return proto.CompactTextString(m) }
func (*ListSourceResponse) ProtoMessage()    {}
func (*ListSourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}
func (m *ListSourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSourceResponse.Unmarshal(m, b)
}
func (m *ListSourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSourceResponse.Marshal(b, m, deterministic)
}
func (m *ListSourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSourceResponse.Merge(m, src)
}
func (m *ListSourceResponse) XXX_Size() int {
	return xxx_messageInfo_ListSourceResponse.Size(m)
}
func (m *ListSourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSourceResponse proto.InternalMessageInfo

func (m *ListSourceResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListSourceResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListSourceResponse) GetSources() []*schema.Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

type ListModuleResponse struct {
	Page                 int32            `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count                int32            `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Modules              []*schema.Module `protobuf:"bytes,3,rep,name=modules,proto3" json:"modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListModuleResponse) Reset()         { *m = ListModuleResponse{} }
func (m *ListModuleResponse) String() string { return proto.CompactTextString(m) }
func (*ListModuleResponse) ProtoMessage()    {}
func (*ListModuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}
func (m *ListModuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModuleResponse.Unmarshal(m, b)
}
func (m *ListModuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModuleResponse.Marshal(b, m, deterministic)
}
func (m *ListModuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModuleResponse.Merge(m, src)
}
func (m *ListModuleResponse) XXX_Size() int {
	return xxx_messageInfo_ListModuleResponse.Size(m)
}
func (m *ListModuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListModuleResponse proto.InternalMessageInfo

func (m *ListModuleResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListModuleResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListModuleResponse) GetModules() []*schema.Module {
	if m != nil {
		return m.Modules
	}
	return nil
}

type ManagedSource struct {
	Source               *schema.Source  `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Manages              *schema.Manages `protobuf:"bytes,2,opt,name=manages,proto3" json:"manages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ManagedSource) Reset()         { *m = ManagedSource{} }
func (m *ManagedSource) String() string { return proto.CompactTextString(m) }
func (*ManagedSource) ProtoMessage()    {}
func (*ManagedSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}
func (m *ManagedSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagedSource.Unmarshal(m, b)
}
func (m *ManagedSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagedSource.Marshal(b, m, deterministic)
}
func (m *ManagedSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagedSource.Merge(m, src)
}
func (m *ManagedSource) XXX_Size() int {
	return xxx_messageInfo_ManagedSource.Size(m)
}
func (m *ManagedSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagedSource.DiscardUnknown(m)
}

var xxx_messageInfo_ManagedSource proto.InternalMessageInfo

func (m *ManagedSource) GetSource() *schema.Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *ManagedSource) GetManages() *schema.Manages {
	if m != nil {
		return m.Manages
	}
	return nil
}

type ManagedModule struct {
	Manages              *schema.Manages `protobuf:"bytes,1,opt,name=manages,proto3" json:"manages,omitempty"`
	Module               *schema.Module  `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ManagedModule) Reset()         { *m = ManagedModule{} }
func (m *ManagedModule) String() string { return proto.CompactTextString(m) }
func (*ManagedModule) ProtoMessage()    {}
func (*ManagedModule) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}
func (m *ManagedModule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagedModule.Unmarshal(m, b)
}
func (m *ManagedModule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagedModule.Marshal(b, m, deterministic)
}
func (m *ManagedModule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagedModule.Merge(m, src)
}
func (m *ManagedModule) XXX_Size() int {
	return xxx_messageInfo_ManagedModule.Size(m)
}
func (m *ManagedModule) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagedModule.DiscardUnknown(m)
}

var xxx_messageInfo_ManagedModule proto.InternalMessageInfo

func (m *ManagedModule) GetManages() *schema.Manages {
	if m != nil {
		return m.Manages
	}
	return nil
}

func (m *ManagedModule) GetModule() *schema.Module {
	if m != nil {
		return m.Module
	}
	return nil
}

type DependencyRequest struct {
	Language             string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Organization         string   `protobuf:"bytes,5,opt,name=organization,proto3" json:"organization,omitempty"`
	Module               string   `protobuf:"bytes,6,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DependencyRequest) Reset()         { *m = DependencyRequest{} }
func (m *DependencyRequest) String() string { return proto.CompactTextString(m) }
func (*DependencyRequest) ProtoMessage()    {}
func (*DependencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}
func (m *DependencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DependencyRequest.Unmarshal(m, b)
}
func (m *DependencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DependencyRequest.Marshal(b, m, deterministic)
}
func (m *DependencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DependencyRequest.Merge(m, src)
}
func (m *DependencyRequest) XXX_Size() int {
	return xxx_messageInfo_DependencyRequest.Size(m)
}
func (m *DependencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DependencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DependencyRequest proto.InternalMessageInfo

func (m *DependencyRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *DependencyRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *DependencyRequest) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

type Dependency struct {
	Depends              *schema.Depends `protobuf:"bytes,1,opt,name=depends,proto3" json:"depends,omitempty"`
	Module               *schema.Module  `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Dependency) Reset()         { *m = Dependency{} }
func (m *Dependency) String() string { return proto.CompactTextString(m) }
func (*Dependency) ProtoMessage()    {}
func (*Dependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}
func (m *Dependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dependency.Unmarshal(m, b)
}
func (m *Dependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dependency.Marshal(b, m, deterministic)
}
func (m *Dependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dependency.Merge(m, src)
}
func (m *Dependency) XXX_Size() int {
	return xxx_messageInfo_Dependency.Size(m)
}
func (m *Dependency) XXX_DiscardUnknown() {
	xxx_messageInfo_Dependency.DiscardUnknown(m)
}

var xxx_messageInfo_Dependency proto.InternalMessageInfo

func (m *Dependency) GetDepends() *schema.Depends {
	if m != nil {
		return m.Depends
	}
	return nil
}

func (m *Dependency) GetModule() *schema.Module {
	if m != nil {
		return m.Module
	}
	return nil
}

type TopologyTier struct {
	Tier                 []*Dependency `protobuf:"bytes,1,rep,name=tier,proto3" json:"tier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TopologyTier) Reset()         { *m = TopologyTier{} }
func (m *TopologyTier) String() string { return proto.CompactTextString(m) }
func (*TopologyTier) ProtoMessage()    {}
func (*TopologyTier) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}
func (m *TopologyTier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopologyTier.Unmarshal(m, b)
}
func (m *TopologyTier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopologyTier.Marshal(b, m, deterministic)
}
func (m *TopologyTier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyTier.Merge(m, src)
}
func (m *TopologyTier) XXX_Size() int {
	return xxx_messageInfo_TopologyTier.Size(m)
}
func (m *TopologyTier) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyTier.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyTier proto.InternalMessageInfo

func (m *TopologyTier) GetTier() []*Dependency {
	if m != nil {
		return m.Tier
	}
	return nil
}

func init() {
	proto.RegisterType((*SourceRequest)(nil), "cloud.deps.dts.api.v1alpha.SourceRequest")
	proto.RegisterType((*ListRequest)(nil), "cloud.deps.dts.api.v1alpha.ListRequest")
	proto.RegisterType((*TrackResponse)(nil), "cloud.deps.dts.api.v1alpha.TrackResponse")
	proto.RegisterType((*ListSourceResponse)(nil), "cloud.deps.dts.api.v1alpha.ListSourceResponse")
	proto.RegisterType((*ListModuleResponse)(nil), "cloud.deps.dts.api.v1alpha.ListModuleResponse")
	proto.RegisterType((*ManagedSource)(nil), "cloud.deps.dts.api.v1alpha.ManagedSource")
	proto.RegisterType((*ManagedModule)(nil), "cloud.deps.dts.api.v1alpha.ManagedModule")
	proto.RegisterType((*DependencyRequest)(nil), "cloud.deps.dts.api.v1alpha.DependencyRequest")
	proto.RegisterType((*Dependency)(nil), "cloud.deps.dts.api.v1alpha.Dependency")
	proto.RegisterType((*TopologyTier)(nil), "cloud.deps.dts.api.v1alpha.TopologyTier")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 864 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0x4f, 0x8f, 0xdb, 0x44,
	0x18, 0xc6, 0x35, 0xd9, 0xcd, 0xfe, 0x79, 0xd3, 0x68, 0xe1, 0x15, 0xb4, 0xc6, 0x15, 0x62, 0xb1,
	0xd0, 0x12, 0x4a, 0x63, 0xa7, 0x01, 0x5a, 0xa8, 0x10, 0x12, 0x50, 0xb1, 0x12, 0xa2, 0x17, 0x77,
	0xc5, 0xa1, 0x17, 0x34, 0xb5, 0x47, 0x8e, 0xd5, 0xc4, 0x63, 0x3c, 0x93, 0xa2, 0x80, 0x90, 0x10,
	0x20, 0x6e, 0x9c, 0x10, 0x08, 0xed, 0x17, 0x40, 0x82, 0x3b, 0x07, 0xbe, 0x01, 0x67, 0x3e, 0x00,
	0x17, 0x3e, 0x08, 0xf2, 0xfc, 0xc9, 0xda, 0xe9, 0x6e, 0xd6, 0x59, 0x6d, 0x4e, 0x9b, 0x19, 0xcf,
	0xf3, 0xbe, 0xbf, 0x79, 0x66, 0xe6, 0xd1, 0x42, 0x57, 0xb0, 0xe2, 0x49, 0x1a, 0x31, 0x3f, 0x2f,
	0xb8, 0xe4, 0xe8, 0x46, 0x63, 0x3e, 0x8d, 0xfd, 0x98, 0xe5, 0xc2, 0x8f, 0xa5, 0xf0, 0x69, 0x9e,
	0xfa, 0x4f, 0x6e, 0xd1, 0x71, 0x3e, 0xa2, 0x6e, 0x2f, 0x49, 0xe5, 0x68, 0xfa, 0xc8, 0x8f, 0xf8,
	0x24, 0x28, 0x17, 0xf4, 0xd5, 0xda, 0x20, 0x66, 0x22, 0xa0, 0x79, 0xaa, 0xa6, 0x74, 0x15, 0xf7,
	0x9d, 0x33, 0x56, 0x4a, 0xbd, 0xd2, 0x14, 0x0c, 0x44, 0x34, 0x62, 0x13, 0xfb, 0xc7, 0x48, 0x1f,
	0x56, 0xa4, 0x49, 0x91, 0x47, 0x7d, 0x16, 0x71, 0x31, 0x13, 0x92, 0x99, 0x61, 0x42, 0x25, 0xfb,
	0x82, 0xce, 0x02, 0x39, 0x4a, 0x8b, 0xf8, 0xb3, 0x9c, 0x16, 0x72, 0x16, 0x24, 0x9c, 0x27, 0x63,
	0x46, 0xf3, 0x54, 0x98, 0x9f, 0xaa, 0x0b, 0xcd, 0x32, 0x2e, 0xa9, 0x4c, 0x79, 0x66, 0xb0, 0xbc,
	0xdf, 0x09, 0x74, 0x1f, 0xf0, 0x69, 0x11, 0xb1, 0x90, 0x7d, 0x3e, 0x65, 0x42, 0xe2, 0xfb, 0xb0,
	0x25, 0xd4, 0x84, 0x43, 0xf6, 0x49, 0xaf, 0x33, 0x7c, 0xcd, 0x3f, 0x7b, 0xff, 0xbe, 0xe1, 0x34,
	0x15, 0x8c, 0x10, 0x3f, 0x85, 0xbd, 0x09, 0xcd, 0x68, 0xc2, 0x26, 0x2c, 0x93, 0x1f, 0xa5, 0x63,
	0x26, 0x9c, 0xd6, 0xfe, 0x46, 0xaf, 0x33, 0xbc, 0x59, 0xab, 0xc5, 0x74, 0xad, 0x7b, 0x2c, 0x67,
	0x59, 0xcc, 0xb2, 0x68, 0x76, 0xbf, 0x26, 0x0a, 0x17, 0x8b, 0x78, 0x77, 0xa0, 0xf3, 0x49, 0x2a,
	0xa4, 0x25, 0x45, 0xd8, 0xcc, 0x69, 0xa2, 0x39, 0xdb, 0xa1, 0xfa, 0x8d, 0xcf, 0x41, 0x3b, 0xe2,
	0xd3, 0x4c, 0x3a, 0x2d, 0x35, 0xa9, 0x07, 0xde, 0xeb, 0xd0, 0x3d, 0x2a, 0x68, 0xf4, 0x38, 0x64,
	0x22, 0xe7, 0x99, 0x60, 0xe8, 0xc2, 0x8e, 0x2c, 0x27, 0xd2, 0x2c, 0x51, 0xf2, 0x9d, 0x70, 0x3e,
	0xf6, 0xbe, 0x23, 0x80, 0x65, 0x1b, 0x6b, 0x8b, 0x91, 0x34, 0xee, 0x86, 0x1f, 0xc2, 0xb6, 0x36,
	0x42, 0x38, 0x1b, 0x6a, 0xdb, 0x2b, 0x58, 0x68, 0x95, 0x73, 0x8a, 0xfb, 0x3c, 0x9e, 0x8e, 0x2f,
	0x48, 0x31, 0x51, 0xda, 0x55, 0x28, 0x4c, 0x37, 0xab, 0xf4, 0x7e, 0x25, 0xd0, 0xd5, 0xa7, 0x12,
	0x6b, 0xc0, 0xcb, 0xb8, 0x1e, 0xf7, 0x60, 0x5b, 0x9f, 0xac, 0x50, 0xc4, 0x9d, 0xe1, 0x8d, 0x26,
	0x64, 0x5a, 0x11, 0x5a, 0x69, 0x15, 0x4d, 0x53, 0x57, 0xeb, 0x92, 0x0b, 0xd7, 0x2d, 0x37, 0xa8,
	0x77, 0x6f, 0xe0, 0x56, 0xb0, 0xcd, 0x08, 0xbd, 0xc7, 0xf0, 0xec, 0xc9, 0xa5, 0xb6, 0xb7, 0xd5,
	0x85, 0x9d, 0x31, 0xcd, 0x92, 0xa9, 0x3d, 0xbd, 0xdd, 0x70, 0x3e, 0x46, 0x0f, 0xae, 0xf0, 0x22,
	0xa1, 0x59, 0xfa, 0xa5, 0x7a, 0x9c, 0x4e, 0x5b, 0x7d, 0xaf, 0xcd, 0xe1, 0xd5, 0x39, 0xd7, 0x96,
	0xfa, 0x6a, 0x9b, 0xfd, 0x4c, 0x00, 0x4e, 0xba, 0x95, 0x26, 0xc4, 0x6a, 0xb4, 0x8a, 0x09, 0x5a,
	0x2f, 0x42, 0x2b, 0xbd, 0x0c, 0x13, 0x3e, 0x86, 0x2b, 0x47, 0x3c, 0xe7, 0x63, 0x9e, 0xcc, 0x8e,
	0x52, 0x56, 0xe0, 0x5d, 0xd8, 0x94, 0x29, 0x2b, 0x1c, 0xa2, 0x2e, 0xe3, 0xc1, 0xb2, 0x82, 0x15,
	0xf3, 0x94, 0x66, 0xf8, 0x63, 0xcb, 0xa6, 0xd4, 0x03, 0x1d, 0xcd, 0x38, 0x83, 0xcd, 0xf2, 0x75,
	0xe0, 0xab, 0xcb, 0xea, 0x54, 0xc2, 0xc2, 0xf5, 0xcf, 0x5b, 0x58, 0x7f, 0xee, 0x9e, 0xf3, 0xed,
	0x3f, 0xff, 0xfd, 0xd4, 0x42, 0x7c, 0xe6, 0x24, 0x9a, 0xf5, 0xcb, 0xc4, 0x6f, 0x08, 0xb4, 0x55,
	0x9a, 0xe0, 0x52, 0x57, 0x6a, 0xa9, 0xea, 0x2e, 0x5d, 0x5a, 0xcb, 0x26, 0xef, 0x65, 0xd5, 0xf9,
	0xba, 0x77, 0x75, 0xb1, 0x73, 0xa0, 0x22, 0xea, 0x2e, 0xb9, 0x31, 0x3c, 0xde, 0x80, 0xae, 0xb6,
	0x7b, 0x7d, 0x7e, 0xd4, 0x83, 0xe7, 0x14, 0x3f, 0x4c, 0x46, 0xe0, 0xf7, 0x04, 0x76, 0x0f, 0x99,
	0xf1, 0x0f, 0x9b, 0xdf, 0x94, 0xe5, 0x9e, 0xd4, 0x52, 0xc7, 0x7b, 0x49, 0x75, 0x7f, 0x01, 0xaf,
	0x2d, 0x76, 0x37, 0xde, 0x0c, 0x08, 0xfe, 0x40, 0x00, 0x0e, 0x99, 0x34, 0x3a, 0x6c, 0x9e, 0x4b,
	0x8d, 0x38, 0x34, 0xb2, 0xb7, 0xaf, 0x38, 0x5c, 0x74, 0x9e, 0xe2, 0xd0, 0xf1, 0x11, 0x0f, 0xc8,
	0xf0, 0xef, 0x56, 0xf5, 0xf9, 0xdb, 0x03, 0xfa, 0x85, 0x40, 0xf7, 0x90, 0x49, 0xfb, 0x41, 0x0a,
	0xec, 0x37, 0x7c, 0x02, 0xe6, 0xc0, 0x1a, 0xbe, 0x18, 0xef, 0xa6, 0x42, 0x3c, 0xc0, 0x57, 0xe6,
	0x88, 0x49, 0x41, 0xf3, 0x51, 0xf0, 0x95, 0x4d, 0x9b, 0xaf, 0x83, 0x78, 0x0e, 0x31, 0x20, 0x78,
	0x4c, 0x60, 0xaf, 0x02, 0x16, 0xa5, 0x6c, 0x6d, 0x68, 0xbe, 0x42, 0xeb, 0xe1, 0xc1, 0xf9, 0x68,
	0x25, 0xc6, 0x80, 0x0c, 0xff, 0x6d, 0xc3, 0x9e, 0x4d, 0x11, 0xeb, 0xe4, 0x6f, 0x04, 0x9e, 0xaf,
	0x39, 0x69, 0x17, 0xac, 0x0b, 0xfb, 0x2d, 0x85, 0x1d, 0x60, 0xbf, 0x89, 0xa3, 0x81, 0x34, 0x34,
	0x03, 0x82, 0x7f, 0x12, 0xb8, 0x7e, 0x2a, 0x69, 0x19, 0x88, 0x2c, 0x5e, 0x95, 0xb7, 0xb7, 0x34,
	0x43, 0x2a, 0xa5, 0xbd, 0x77, 0x15, 0xf1, 0x6d, 0x7c, 0x73, 0x25, 0xe2, 0x40, 0x2a, 0xac, 0x01,
	0xc1, 0x3f, 0x08, 0x5c, 0x5b, 0xb8, 0x13, 0xeb, 0x36, 0xf9, 0x8e, 0x42, 0xbe, 0x85, 0x41, 0xb3,
	0xbb, 0x51, 0xb5, 0xf9, 0x2f, 0x02, 0x2f, 0x9e, 0x41, 0xbb, 0x6e, 0xa3, 0xdf, 0x53, 0xd4, 0x6f,
	0xe3, 0xed, 0x15, 0xa9, 0xe7, 0x56, 0x7f, 0xb0, 0xfb, 0x70, 0xdb, 0x48, 0x1f, 0x6d, 0xa9, 0x7f,
	0xc9, 0xdf, 0xf8, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x62, 0xfa, 0xdb, 0x80, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SourceServiceClient is the client API for SourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SourceServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListSourceResponse, error)
	Track(ctx context.Context, in *SourceRequest, opts ...grpc.CallOption) (*TrackResponse, error)
}

type sourceServiceClient struct {
	cc *grpc.ClientConn
}

func NewSourceServiceClient(cc *grpc.ClientConn) SourceServiceClient {
	return &sourceServiceClient{cc}
}

func (c *sourceServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListSourceResponse, error) {
	out := new(ListSourceResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.dts.api.v1alpha.SourceService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceServiceClient) Track(ctx context.Context, in *SourceRequest, opts ...grpc.CallOption) (*TrackResponse, error) {
	out := new(TrackResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.dts.api.v1alpha.SourceService/Track", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceServiceServer is the server API for SourceService service.
type SourceServiceServer interface {
	List(context.Context, *ListRequest) (*ListSourceResponse, error)
	Track(context.Context, *SourceRequest) (*TrackResponse, error)
}

// UnimplementedSourceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSourceServiceServer struct {
}

func (*UnimplementedSourceServiceServer) List(ctx context.Context, req *ListRequest) (*ListSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedSourceServiceServer) Track(ctx context.Context, req *SourceRequest) (*TrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Track not implemented")
}

func RegisterSourceServiceServer(s *grpc.Server, srv SourceServiceServer) {
	s.RegisterService(&_SourceService_serviceDesc, srv)
}

func _SourceService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.dts.api.v1alpha.SourceService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceService_Track_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).Track(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.dts.api.v1alpha.SourceService/Track",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).Track(ctx, req.(*SourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SourceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.deps.dts.api.v1alpha.SourceService",
	HandlerType: (*SourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SourceService_List_Handler,
		},
		{
			MethodName: "Track",
			Handler:    _SourceService_Track_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// ModuleServiceClient is the client API for ModuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModuleServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListModuleResponse, error)
	GetSource(ctx context.Context, in *schema.Module, opts ...grpc.CallOption) (ModuleService_GetSourceClient, error)
	GetManaged(ctx context.Context, in *schema.Source, opts ...grpc.CallOption) (ModuleService_GetManagedClient, error)
}

type moduleServiceClient struct {
	cc *grpc.ClientConn
}

func NewModuleServiceClient(cc *grpc.ClientConn) ModuleServiceClient {
	return &moduleServiceClient{cc}
}

func (c *moduleServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListModuleResponse, error) {
	out := new(ListModuleResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.dts.api.v1alpha.ModuleService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) GetSource(ctx context.Context, in *schema.Module, opts ...grpc.CallOption) (ModuleService_GetSourceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ModuleService_serviceDesc.Streams[0], "/cloud.deps.dts.api.v1alpha.ModuleService/GetSource", opts...)
	if err != nil {
		return nil, err
	}
	x := &moduleServiceGetSourceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ModuleService_GetSourceClient interface {
	Recv() (*ManagedSource, error)
	grpc.ClientStream
}

type moduleServiceGetSourceClient struct {
	grpc.ClientStream
}

func (x *moduleServiceGetSourceClient) Recv() (*ManagedSource, error) {
	m := new(ManagedSource)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *moduleServiceClient) GetManaged(ctx context.Context, in *schema.Source, opts ...grpc.CallOption) (ModuleService_GetManagedClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ModuleService_serviceDesc.Streams[1], "/cloud.deps.dts.api.v1alpha.ModuleService/GetManaged", opts...)
	if err != nil {
		return nil, err
	}
	x := &moduleServiceGetManagedClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ModuleService_GetManagedClient interface {
	Recv() (*ManagedModule, error)
	grpc.ClientStream
}

type moduleServiceGetManagedClient struct {
	grpc.ClientStream
}

func (x *moduleServiceGetManagedClient) Recv() (*ManagedModule, error) {
	m := new(ManagedModule)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ModuleServiceServer is the server API for ModuleService service.
type ModuleServiceServer interface {
	List(context.Context, *ListRequest) (*ListModuleResponse, error)
	GetSource(*schema.Module, ModuleService_GetSourceServer) error
	GetManaged(*schema.Source, ModuleService_GetManagedServer) error
}

// UnimplementedModuleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedModuleServiceServer struct {
}

func (*UnimplementedModuleServiceServer) List(ctx context.Context, req *ListRequest) (*ListModuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedModuleServiceServer) GetSource(req *schema.Module, srv ModuleService_GetSourceServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSource not implemented")
}
func (*UnimplementedModuleServiceServer) GetManaged(req *schema.Source, srv ModuleService_GetManagedServer) error {
	return status.Errorf(codes.Unimplemented, "method GetManaged not implemented")
}

func RegisterModuleServiceServer(s *grpc.Server, srv ModuleServiceServer) {
	s.RegisterService(&_ModuleService_serviceDesc, srv)
}

func _ModuleService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.dts.api.v1alpha.ModuleService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_GetSource_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(schema.Module)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModuleServiceServer).GetSource(m, &moduleServiceGetSourceServer{stream})
}

type ModuleService_GetSourceServer interface {
	Send(*ManagedSource) error
	grpc.ServerStream
}

type moduleServiceGetSourceServer struct {
	grpc.ServerStream
}

func (x *moduleServiceGetSourceServer) Send(m *ManagedSource) error {
	return x.ServerStream.SendMsg(m)
}

func _ModuleService_GetManaged_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(schema.Source)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModuleServiceServer).GetManaged(m, &moduleServiceGetManagedServer{stream})
}

type ModuleService_GetManagedServer interface {
	Send(*ManagedModule) error
	grpc.ServerStream
}

type moduleServiceGetManagedServer struct {
	grpc.ServerStream
}

func (x *moduleServiceGetManagedServer) Send(m *ManagedModule) error {
	return x.ServerStream.SendMsg(m)
}

var _ModuleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.deps.dts.api.v1alpha.ModuleService",
	HandlerType: (*ModuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ModuleService_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSource",
			Handler:       _ModuleService_GetSource_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetManaged",
			Handler:       _ModuleService_GetManaged_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}

// DependencyServiceClient is the client API for DependencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DependencyServiceClient interface {
	GetDependents(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (DependencyService_GetDependentsClient, error)
	GetDependencies(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (DependencyService_GetDependenciesClient, error)
}

type dependencyServiceClient struct {
	cc *grpc.ClientConn
}

func NewDependencyServiceClient(cc *grpc.ClientConn) DependencyServiceClient {
	return &dependencyServiceClient{cc}
}

func (c *dependencyServiceClient) GetDependents(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (DependencyService_GetDependentsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DependencyService_serviceDesc.Streams[0], "/cloud.deps.dts.api.v1alpha.DependencyService/GetDependents", opts...)
	if err != nil {
		return nil, err
	}
	x := &dependencyServiceGetDependentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DependencyService_GetDependentsClient interface {
	Recv() (*Dependency, error)
	grpc.ClientStream
}

type dependencyServiceGetDependentsClient struct {
	grpc.ClientStream
}

func (x *dependencyServiceGetDependentsClient) Recv() (*Dependency, error) {
	m := new(Dependency)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dependencyServiceClient) GetDependencies(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (DependencyService_GetDependenciesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DependencyService_serviceDesc.Streams[1], "/cloud.deps.dts.api.v1alpha.DependencyService/GetDependencies", opts...)
	if err != nil {
		return nil, err
	}
	x := &dependencyServiceGetDependenciesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DependencyService_GetDependenciesClient interface {
	Recv() (*Dependency, error)
	grpc.ClientStream
}

type dependencyServiceGetDependenciesClient struct {
	grpc.ClientStream
}

func (x *dependencyServiceGetDependenciesClient) Recv() (*Dependency, error) {
	m := new(Dependency)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DependencyServiceServer is the server API for DependencyService service.
type DependencyServiceServer interface {
	GetDependents(*DependencyRequest, DependencyService_GetDependentsServer) error
	GetDependencies(*DependencyRequest, DependencyService_GetDependenciesServer) error
}

// UnimplementedDependencyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDependencyServiceServer struct {
}

func (*UnimplementedDependencyServiceServer) GetDependents(req *DependencyRequest, srv DependencyService_GetDependentsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDependents not implemented")
}
func (*UnimplementedDependencyServiceServer) GetDependencies(req *DependencyRequest, srv DependencyService_GetDependenciesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDependencies not implemented")
}

func RegisterDependencyServiceServer(s *grpc.Server, srv DependencyServiceServer) {
	s.RegisterService(&_DependencyService_serviceDesc, srv)
}

func _DependencyService_GetDependents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DependencyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DependencyServiceServer).GetDependents(m, &dependencyServiceGetDependentsServer{stream})
}

type DependencyService_GetDependentsServer interface {
	Send(*Dependency) error
	grpc.ServerStream
}

type dependencyServiceGetDependentsServer struct {
	grpc.ServerStream
}

func (x *dependencyServiceGetDependentsServer) Send(m *Dependency) error {
	return x.ServerStream.SendMsg(m)
}

func _DependencyService_GetDependencies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DependencyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DependencyServiceServer).GetDependencies(m, &dependencyServiceGetDependenciesServer{stream})
}

type DependencyService_GetDependenciesServer interface {
	Send(*Dependency) error
	grpc.ServerStream
}

type dependencyServiceGetDependenciesServer struct {
	grpc.ServerStream
}

func (x *dependencyServiceGetDependenciesServer) Send(m *Dependency) error {
	return x.ServerStream.SendMsg(m)
}

var _DependencyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.deps.dts.api.v1alpha.DependencyService",
	HandlerType: (*DependencyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDependents",
			Handler:       _DependencyService_GetDependents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetDependencies",
			Handler:       _DependencyService_GetDependencies_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}

// TopologyServiceClient is the client API for TopologyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TopologyServiceClient interface {
	GetDependentsTopology(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (TopologyService_GetDependentsTopologyClient, error)
	GetDependentsTopologyTiered(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (TopologyService_GetDependentsTopologyTieredClient, error)
	GetDependenciesTopology(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (TopologyService_GetDependenciesTopologyClient, error)
	GetDependenciesTopologyTiered(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (TopologyService_GetDependenciesTopologyTieredClient, error)
}

type topologyServiceClient struct {
	cc *grpc.ClientConn
}

func NewTopologyServiceClient(cc *grpc.ClientConn) TopologyServiceClient {
	return &topologyServiceClient{cc}
}

func (c *topologyServiceClient) GetDependentsTopology(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (TopologyService_GetDependentsTopologyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TopologyService_serviceDesc.Streams[0], "/cloud.deps.dts.api.v1alpha.TopologyService/GetDependentsTopology", opts...)
	if err != nil {
		return nil, err
	}
	x := &topologyServiceGetDependentsTopologyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TopologyService_GetDependentsTopologyClient interface {
	Recv() (*Dependency, error)
	grpc.ClientStream
}

type topologyServiceGetDependentsTopologyClient struct {
	grpc.ClientStream
}

func (x *topologyServiceGetDependentsTopologyClient) Recv() (*Dependency, error) {
	m := new(Dependency)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *topologyServiceClient) GetDependentsTopologyTiered(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (TopologyService_GetDependentsTopologyTieredClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TopologyService_serviceDesc.Streams[1], "/cloud.deps.dts.api.v1alpha.TopologyService/GetDependentsTopologyTiered", opts...)
	if err != nil {
		return nil, err
	}
	x := &topologyServiceGetDependentsTopologyTieredClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TopologyService_GetDependentsTopologyTieredClient interface {
	Recv() (*TopologyTier, error)
	grpc.ClientStream
}

type topologyServiceGetDependentsTopologyTieredClient struct {
	grpc.ClientStream
}

func (x *topologyServiceGetDependentsTopologyTieredClient) Recv() (*TopologyTier, error) {
	m := new(TopologyTier)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *topologyServiceClient) GetDependenciesTopology(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (TopologyService_GetDependenciesTopologyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TopologyService_serviceDesc.Streams[2], "/cloud.deps.dts.api.v1alpha.TopologyService/GetDependenciesTopology", opts...)
	if err != nil {
		return nil, err
	}
	x := &topologyServiceGetDependenciesTopologyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TopologyService_GetDependenciesTopologyClient interface {
	Recv() (*Dependency, error)
	grpc.ClientStream
}

type topologyServiceGetDependenciesTopologyClient struct {
	grpc.ClientStream
}

func (x *topologyServiceGetDependenciesTopologyClient) Recv() (*Dependency, error) {
	m := new(Dependency)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *topologyServiceClient) GetDependenciesTopologyTiered(ctx context.Context, in *DependencyRequest, opts ...grpc.CallOption) (TopologyService_GetDependenciesTopologyTieredClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TopologyService_serviceDesc.Streams[3], "/cloud.deps.dts.api.v1alpha.TopologyService/GetDependenciesTopologyTiered", opts...)
	if err != nil {
		return nil, err
	}
	x := &topologyServiceGetDependenciesTopologyTieredClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TopologyService_GetDependenciesTopologyTieredClient interface {
	Recv() (*TopologyTier, error)
	grpc.ClientStream
}

type topologyServiceGetDependenciesTopologyTieredClient struct {
	grpc.ClientStream
}

func (x *topologyServiceGetDependenciesTopologyTieredClient) Recv() (*TopologyTier, error) {
	m := new(TopologyTier)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TopologyServiceServer is the server API for TopologyService service.
type TopologyServiceServer interface {
	GetDependentsTopology(*DependencyRequest, TopologyService_GetDependentsTopologyServer) error
	GetDependentsTopologyTiered(*DependencyRequest, TopologyService_GetDependentsTopologyTieredServer) error
	GetDependenciesTopology(*DependencyRequest, TopologyService_GetDependenciesTopologyServer) error
	GetDependenciesTopologyTiered(*DependencyRequest, TopologyService_GetDependenciesTopologyTieredServer) error
}

// UnimplementedTopologyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTopologyServiceServer struct {
}

func (*UnimplementedTopologyServiceServer) GetDependentsTopology(req *DependencyRequest, srv TopologyService_GetDependentsTopologyServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDependentsTopology not implemented")
}
func (*UnimplementedTopologyServiceServer) GetDependentsTopologyTiered(req *DependencyRequest, srv TopologyService_GetDependentsTopologyTieredServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDependentsTopologyTiered not implemented")
}
func (*UnimplementedTopologyServiceServer) GetDependenciesTopology(req *DependencyRequest, srv TopologyService_GetDependenciesTopologyServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDependenciesTopology not implemented")
}
func (*UnimplementedTopologyServiceServer) GetDependenciesTopologyTiered(req *DependencyRequest, srv TopologyService_GetDependenciesTopologyTieredServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDependenciesTopologyTiered not implemented")
}

func RegisterTopologyServiceServer(s *grpc.Server, srv TopologyServiceServer) {
	s.RegisterService(&_TopologyService_serviceDesc, srv)
}

func _TopologyService_GetDependentsTopology_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DependencyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TopologyServiceServer).GetDependentsTopology(m, &topologyServiceGetDependentsTopologyServer{stream})
}

type TopologyService_GetDependentsTopologyServer interface {
	Send(*Dependency) error
	grpc.ServerStream
}

type topologyServiceGetDependentsTopologyServer struct {
	grpc.ServerStream
}

func (x *topologyServiceGetDependentsTopologyServer) Send(m *Dependency) error {
	return x.ServerStream.SendMsg(m)
}

func _TopologyService_GetDependentsTopologyTiered_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DependencyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TopologyServiceServer).GetDependentsTopologyTiered(m, &topologyServiceGetDependentsTopologyTieredServer{stream})
}

type TopologyService_GetDependentsTopologyTieredServer interface {
	Send(*TopologyTier) error
	grpc.ServerStream
}

type topologyServiceGetDependentsTopologyTieredServer struct {
	grpc.ServerStream
}

func (x *topologyServiceGetDependentsTopologyTieredServer) Send(m *TopologyTier) error {
	return x.ServerStream.SendMsg(m)
}

func _TopologyService_GetDependenciesTopology_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DependencyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TopologyServiceServer).GetDependenciesTopology(m, &topologyServiceGetDependenciesTopologyServer{stream})
}

type TopologyService_GetDependenciesTopologyServer interface {
	Send(*Dependency) error
	grpc.ServerStream
}

type topologyServiceGetDependenciesTopologyServer struct {
	grpc.ServerStream
}

func (x *topologyServiceGetDependenciesTopologyServer) Send(m *Dependency) error {
	return x.ServerStream.SendMsg(m)
}

func _TopologyService_GetDependenciesTopologyTiered_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DependencyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TopologyServiceServer).GetDependenciesTopologyTiered(m, &topologyServiceGetDependenciesTopologyTieredServer{stream})
}

type TopologyService_GetDependenciesTopologyTieredServer interface {
	Send(*TopologyTier) error
	grpc.ServerStream
}

type topologyServiceGetDependenciesTopologyTieredServer struct {
	grpc.ServerStream
}

func (x *topologyServiceGetDependenciesTopologyTieredServer) Send(m *TopologyTier) error {
	return x.ServerStream.SendMsg(m)
}

var _TopologyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.deps.dts.api.v1alpha.TopologyService",
	HandlerType: (*TopologyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDependentsTopology",
			Handler:       _TopologyService_GetDependentsTopology_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetDependentsTopologyTiered",
			Handler:       _TopologyService_GetDependentsTopologyTiered_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetDependenciesTopology",
			Handler:       _TopologyService_GetDependenciesTopology_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetDependenciesTopologyTiered",
			Handler:       _TopologyService_GetDependenciesTopologyTiered_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
