// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dts.proto

package api

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import api "github.com/deps-cloud/des/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Direction int32

const (
	Direction_UPSTREAM   Direction = 0
	Direction_DOWNSTREAM Direction = 1
)

var Direction_name = map[int32]string{
	0: "UPSTREAM",
	1: "DOWNSTREAM",
}
var Direction_value = map[string]int32{
	"UPSTREAM":   0,
	"DOWNSTREAM": 1,
}

func (x Direction) String() string {
	return proto.EnumName(Direction_name, int32(x))
}
func (Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{0}
}

type SourceInformation struct {
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceInformation) Reset()         { *m = SourceInformation{} }
func (m *SourceInformation) String() string { return proto.CompactTextString(m) }
func (*SourceInformation) ProtoMessage()    {}
func (*SourceInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{0}
}
func (m *SourceInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceInformation.Unmarshal(m, b)
}
func (m *SourceInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceInformation.Marshal(b, m, deterministic)
}
func (dst *SourceInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceInformation.Merge(dst, src)
}
func (m *SourceInformation) XXX_Size() int {
	return xxx_messageInfo_SourceInformation.Size(m)
}
func (m *SourceInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceInformation.DiscardUnknown(m)
}

var xxx_messageInfo_SourceInformation proto.InternalMessageInfo

func (m *SourceInformation) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type DependencyId struct {
	Organization         string   `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	Module               string   `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DependencyId) Reset()         { *m = DependencyId{} }
func (m *DependencyId) String() string { return proto.CompactTextString(m) }
func (*DependencyId) ProtoMessage()    {}
func (*DependencyId) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{1}
}
func (m *DependencyId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DependencyId.Unmarshal(m, b)
}
func (m *DependencyId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DependencyId.Marshal(b, m, deterministic)
}
func (dst *DependencyId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DependencyId.Merge(dst, src)
}
func (m *DependencyId) XXX_Size() int {
	return xxx_messageInfo_DependencyId.Size(m)
}
func (m *DependencyId) XXX_DiscardUnknown() {
	xxx_messageInfo_DependencyId.DiscardUnknown(m)
}

var xxx_messageInfo_DependencyId proto.InternalMessageInfo

func (m *DependencyId) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *DependencyId) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

type PutRequest struct {
	SourceInformation    *SourceInformation              `protobuf:"bytes,1,opt,name=sourceInformation,proto3" json:"sourceInformation,omitempty"`
	ManagementFiles      []*api.DependencyManagementFile `protobuf:"bytes,2,rep,name=managementFiles,proto3" json:"managementFiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{2}
}
func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (dst *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(dst, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetSourceInformation() *SourceInformation {
	if m != nil {
		return m.SourceInformation
	}
	return nil
}

func (m *PutRequest) GetManagementFiles() []*api.DependencyManagementFile {
	if m != nil {
		return m.ManagementFiles
	}
	return nil
}

type PutResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{3}
}
func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (dst *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(dst, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PutResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Request struct {
	Language             string    `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	System               string    `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`
	Organization         string    `protobuf:"bytes,5,opt,name=organization,proto3" json:"organization,omitempty"`
	Module               string    `protobuf:"bytes,6,opt,name=module,proto3" json:"module,omitempty"`
	Direction            Direction `protobuf:"varint,7,opt,name=direction,proto3,enum=cloud.deps.rds.api.Direction" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{4}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Request) GetSystem() string {
	if m != nil {
		return m.System
	}
	return ""
}

func (m *Request) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *Request) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *Request) GetDirection() Direction {
	if m != nil {
		return m.Direction
	}
	return Direction_UPSTREAM
}

type Response struct {
	Dependency           *DependencyId `protobuf:"bytes,1,opt,name=dependency,proto3" json:"dependency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{5}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetDependency() *DependencyId {
	if m != nil {
		return m.Dependency
	}
	return nil
}

type TieredResponse struct {
	Tier                 []*DependencyId `protobuf:"bytes,1,rep,name=tier,proto3" json:"tier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TieredResponse) Reset()         { *m = TieredResponse{} }
func (m *TieredResponse) String() string { return proto.CompactTextString(m) }
func (*TieredResponse) ProtoMessage()    {}
func (*TieredResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{6}
}
func (m *TieredResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TieredResponse.Unmarshal(m, b)
}
func (m *TieredResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TieredResponse.Marshal(b, m, deterministic)
}
func (dst *TieredResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TieredResponse.Merge(dst, src)
}
func (m *TieredResponse) XXX_Size() int {
	return xxx_messageInfo_TieredResponse.Size(m)
}
func (m *TieredResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TieredResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TieredResponse proto.InternalMessageInfo

func (m *TieredResponse) GetTier() []*DependencyId {
	if m != nil {
		return m.Tier
	}
	return nil
}

type GetSourcesRequest struct {
	Language             string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Organization         string   `protobuf:"bytes,5,opt,name=organization,proto3" json:"organization,omitempty"`
	Module               string   `protobuf:"bytes,6,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSourcesRequest) Reset()         { *m = GetSourcesRequest{} }
func (m *GetSourcesRequest) String() string { return proto.CompactTextString(m) }
func (*GetSourcesRequest) ProtoMessage()    {}
func (*GetSourcesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{7}
}
func (m *GetSourcesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSourcesRequest.Unmarshal(m, b)
}
func (m *GetSourcesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSourcesRequest.Marshal(b, m, deterministic)
}
func (dst *GetSourcesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSourcesRequest.Merge(dst, src)
}
func (m *GetSourcesRequest) XXX_Size() int {
	return xxx_messageInfo_GetSourcesRequest.Size(m)
}
func (m *GetSourcesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSourcesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSourcesRequest proto.InternalMessageInfo

func (m *GetSourcesRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *GetSourcesRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *GetSourcesRequest) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

type GetSourcesResponse struct {
	Source               *SourceInformation `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetSourcesResponse) Reset()         { *m = GetSourcesResponse{} }
func (m *GetSourcesResponse) String() string { return proto.CompactTextString(m) }
func (*GetSourcesResponse) ProtoMessage()    {}
func (*GetSourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{8}
}
func (m *GetSourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSourcesResponse.Unmarshal(m, b)
}
func (m *GetSourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSourcesResponse.Marshal(b, m, deterministic)
}
func (dst *GetSourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSourcesResponse.Merge(dst, src)
}
func (m *GetSourcesResponse) XXX_Size() int {
	return xxx_messageInfo_GetSourcesResponse.Size(m)
}
func (m *GetSourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSourcesResponse proto.InternalMessageInfo

func (m *GetSourcesResponse) GetSource() *SourceInformation {
	if m != nil {
		return m.Source
	}
	return nil
}

type ListLanguagesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLanguagesRequest) Reset()         { *m = ListLanguagesRequest{} }
func (m *ListLanguagesRequest) String() string { return proto.CompactTextString(m) }
func (*ListLanguagesRequest) ProtoMessage()    {}
func (*ListLanguagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{9}
}
func (m *ListLanguagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLanguagesRequest.Unmarshal(m, b)
}
func (m *ListLanguagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLanguagesRequest.Marshal(b, m, deterministic)
}
func (dst *ListLanguagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLanguagesRequest.Merge(dst, src)
}
func (m *ListLanguagesRequest) XXX_Size() int {
	return xxx_messageInfo_ListLanguagesRequest.Size(m)
}
func (m *ListLanguagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLanguagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListLanguagesRequest proto.InternalMessageInfo

type ListLanguagesResponse struct {
	Languages            []string `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLanguagesResponse) Reset()         { *m = ListLanguagesResponse{} }
func (m *ListLanguagesResponse) String() string { return proto.CompactTextString(m) }
func (*ListLanguagesResponse) ProtoMessage()    {}
func (*ListLanguagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{10}
}
func (m *ListLanguagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLanguagesResponse.Unmarshal(m, b)
}
func (m *ListLanguagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLanguagesResponse.Marshal(b, m, deterministic)
}
func (dst *ListLanguagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLanguagesResponse.Merge(dst, src)
}
func (m *ListLanguagesResponse) XXX_Size() int {
	return xxx_messageInfo_ListLanguagesResponse.Size(m)
}
func (m *ListLanguagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLanguagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListLanguagesResponse proto.InternalMessageInfo

func (m *ListLanguagesResponse) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

type ListOrganizationsRequest struct {
	Language             string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrganizationsRequest) Reset()         { *m = ListOrganizationsRequest{} }
func (m *ListOrganizationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListOrganizationsRequest) ProtoMessage()    {}
func (*ListOrganizationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{11}
}
func (m *ListOrganizationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrganizationsRequest.Unmarshal(m, b)
}
func (m *ListOrganizationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrganizationsRequest.Marshal(b, m, deterministic)
}
func (dst *ListOrganizationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrganizationsRequest.Merge(dst, src)
}
func (m *ListOrganizationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListOrganizationsRequest.Size(m)
}
func (m *ListOrganizationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrganizationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrganizationsRequest proto.InternalMessageInfo

func (m *ListOrganizationsRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type ListOrganizationsResponse struct {
	Language             string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Organizations        []string `protobuf:"bytes,2,rep,name=organizations,proto3" json:"organizations,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrganizationsResponse) Reset()         { *m = ListOrganizationsResponse{} }
func (m *ListOrganizationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListOrganizationsResponse) ProtoMessage()    {}
func (*ListOrganizationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{12}
}
func (m *ListOrganizationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrganizationsResponse.Unmarshal(m, b)
}
func (m *ListOrganizationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrganizationsResponse.Marshal(b, m, deterministic)
}
func (dst *ListOrganizationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrganizationsResponse.Merge(dst, src)
}
func (m *ListOrganizationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListOrganizationsResponse.Size(m)
}
func (m *ListOrganizationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrganizationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrganizationsResponse proto.InternalMessageInfo

func (m *ListOrganizationsResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ListOrganizationsResponse) GetOrganizations() []string {
	if m != nil {
		return m.Organizations
	}
	return nil
}

type ListModulesRequest struct {
	Language             string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Organization         string   `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListModulesRequest) Reset()         { *m = ListModulesRequest{} }
func (m *ListModulesRequest) String() string { return proto.CompactTextString(m) }
func (*ListModulesRequest) ProtoMessage()    {}
func (*ListModulesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{13}
}
func (m *ListModulesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModulesRequest.Unmarshal(m, b)
}
func (m *ListModulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModulesRequest.Marshal(b, m, deterministic)
}
func (dst *ListModulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModulesRequest.Merge(dst, src)
}
func (m *ListModulesRequest) XXX_Size() int {
	return xxx_messageInfo_ListModulesRequest.Size(m)
}
func (m *ListModulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListModulesRequest proto.InternalMessageInfo

func (m *ListModulesRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ListModulesRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

type ListModulesResponse struct {
	Language             string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Organization         string   `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	Modules              []string `protobuf:"bytes,3,rep,name=modules,proto3" json:"modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListModulesResponse) Reset()         { *m = ListModulesResponse{} }
func (m *ListModulesResponse) String() string { return proto.CompactTextString(m) }
func (*ListModulesResponse) ProtoMessage()    {}
func (*ListModulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dts_4e337ae99d5cade8, []int{14}
}
func (m *ListModulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModulesResponse.Unmarshal(m, b)
}
func (m *ListModulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModulesResponse.Marshal(b, m, deterministic)
}
func (dst *ListModulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModulesResponse.Merge(dst, src)
}
func (m *ListModulesResponse) XXX_Size() int {
	return xxx_messageInfo_ListModulesResponse.Size(m)
}
func (m *ListModulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListModulesResponse proto.InternalMessageInfo

func (m *ListModulesResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ListModulesResponse) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *ListModulesResponse) GetModules() []string {
	if m != nil {
		return m.Modules
	}
	return nil
}

func init() {
	proto.RegisterType((*SourceInformation)(nil), "cloud.deps.rds.api.SourceInformation")
	proto.RegisterType((*DependencyId)(nil), "cloud.deps.rds.api.DependencyId")
	proto.RegisterType((*PutRequest)(nil), "cloud.deps.rds.api.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "cloud.deps.rds.api.PutResponse")
	proto.RegisterType((*Request)(nil), "cloud.deps.rds.api.Request")
	proto.RegisterType((*Response)(nil), "cloud.deps.rds.api.Response")
	proto.RegisterType((*TieredResponse)(nil), "cloud.deps.rds.api.TieredResponse")
	proto.RegisterType((*GetSourcesRequest)(nil), "cloud.deps.rds.api.GetSourcesRequest")
	proto.RegisterType((*GetSourcesResponse)(nil), "cloud.deps.rds.api.GetSourcesResponse")
	proto.RegisterType((*ListLanguagesRequest)(nil), "cloud.deps.rds.api.ListLanguagesRequest")
	proto.RegisterType((*ListLanguagesResponse)(nil), "cloud.deps.rds.api.ListLanguagesResponse")
	proto.RegisterType((*ListOrganizationsRequest)(nil), "cloud.deps.rds.api.ListOrganizationsRequest")
	proto.RegisterType((*ListOrganizationsResponse)(nil), "cloud.deps.rds.api.ListOrganizationsResponse")
	proto.RegisterType((*ListModulesRequest)(nil), "cloud.deps.rds.api.ListModulesRequest")
	proto.RegisterType((*ListModulesResponse)(nil), "cloud.deps.rds.api.ListModulesResponse")
	proto.RegisterEnum("cloud.deps.rds.api.Direction", Direction_name, Direction_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DependencyTrackingServiceClient is the client API for DependencyTrackingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DependencyTrackingServiceClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	GetDependencies(ctx context.Context, in *Request, opts ...grpc.CallOption) (DependencyTrackingService_GetDependenciesClient, error)
	GetTopology(ctx context.Context, in *Request, opts ...grpc.CallOption) (DependencyTrackingService_GetTopologyClient, error)
	GetTopologyTiered(ctx context.Context, in *Request, opts ...grpc.CallOption) (DependencyTrackingService_GetTopologyTieredClient, error)
	GetSources(ctx context.Context, in *GetSourcesRequest, opts ...grpc.CallOption) (DependencyTrackingService_GetSourcesClient, error)
	ListLanguages(ctx context.Context, in *ListLanguagesRequest, opts ...grpc.CallOption) (*ListLanguagesResponse, error)
	ListOrganizations(ctx context.Context, in *ListOrganizationsRequest, opts ...grpc.CallOption) (*ListOrganizationsResponse, error)
	ListModules(ctx context.Context, in *ListModulesRequest, opts ...grpc.CallOption) (*ListModulesResponse, error)
}

type dependencyTrackingServiceClient struct {
	cc *grpc.ClientConn
}

func NewDependencyTrackingServiceClient(cc *grpc.ClientConn) DependencyTrackingServiceClient {
	return &dependencyTrackingServiceClient{cc}
}

func (c *dependencyTrackingServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.rds.api.DependencyTrackingService/put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dependencyTrackingServiceClient) GetDependencies(ctx context.Context, in *Request, opts ...grpc.CallOption) (DependencyTrackingService_GetDependenciesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DependencyTrackingService_serviceDesc.Streams[0], "/cloud.deps.rds.api.DependencyTrackingService/getDependencies", opts...)
	if err != nil {
		return nil, err
	}
	x := &dependencyTrackingServiceGetDependenciesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DependencyTrackingService_GetDependenciesClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type dependencyTrackingServiceGetDependenciesClient struct {
	grpc.ClientStream
}

func (x *dependencyTrackingServiceGetDependenciesClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dependencyTrackingServiceClient) GetTopology(ctx context.Context, in *Request, opts ...grpc.CallOption) (DependencyTrackingService_GetTopologyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DependencyTrackingService_serviceDesc.Streams[1], "/cloud.deps.rds.api.DependencyTrackingService/getTopology", opts...)
	if err != nil {
		return nil, err
	}
	x := &dependencyTrackingServiceGetTopologyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DependencyTrackingService_GetTopologyClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type dependencyTrackingServiceGetTopologyClient struct {
	grpc.ClientStream
}

func (x *dependencyTrackingServiceGetTopologyClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dependencyTrackingServiceClient) GetTopologyTiered(ctx context.Context, in *Request, opts ...grpc.CallOption) (DependencyTrackingService_GetTopologyTieredClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DependencyTrackingService_serviceDesc.Streams[2], "/cloud.deps.rds.api.DependencyTrackingService/getTopologyTiered", opts...)
	if err != nil {
		return nil, err
	}
	x := &dependencyTrackingServiceGetTopologyTieredClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DependencyTrackingService_GetTopologyTieredClient interface {
	Recv() (*TieredResponse, error)
	grpc.ClientStream
}

type dependencyTrackingServiceGetTopologyTieredClient struct {
	grpc.ClientStream
}

func (x *dependencyTrackingServiceGetTopologyTieredClient) Recv() (*TieredResponse, error) {
	m := new(TieredResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dependencyTrackingServiceClient) GetSources(ctx context.Context, in *GetSourcesRequest, opts ...grpc.CallOption) (DependencyTrackingService_GetSourcesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DependencyTrackingService_serviceDesc.Streams[3], "/cloud.deps.rds.api.DependencyTrackingService/getSources", opts...)
	if err != nil {
		return nil, err
	}
	x := &dependencyTrackingServiceGetSourcesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DependencyTrackingService_GetSourcesClient interface {
	Recv() (*GetSourcesResponse, error)
	grpc.ClientStream
}

type dependencyTrackingServiceGetSourcesClient struct {
	grpc.ClientStream
}

func (x *dependencyTrackingServiceGetSourcesClient) Recv() (*GetSourcesResponse, error) {
	m := new(GetSourcesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dependencyTrackingServiceClient) ListLanguages(ctx context.Context, in *ListLanguagesRequest, opts ...grpc.CallOption) (*ListLanguagesResponse, error) {
	out := new(ListLanguagesResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.rds.api.DependencyTrackingService/listLanguages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dependencyTrackingServiceClient) ListOrganizations(ctx context.Context, in *ListOrganizationsRequest, opts ...grpc.CallOption) (*ListOrganizationsResponse, error) {
	out := new(ListOrganizationsResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.rds.api.DependencyTrackingService/listOrganizations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dependencyTrackingServiceClient) ListModules(ctx context.Context, in *ListModulesRequest, opts ...grpc.CallOption) (*ListModulesResponse, error) {
	out := new(ListModulesResponse)
	err := c.cc.Invoke(ctx, "/cloud.deps.rds.api.DependencyTrackingService/listModules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DependencyTrackingServiceServer is the server API for DependencyTrackingService service.
type DependencyTrackingServiceServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	GetDependencies(*Request, DependencyTrackingService_GetDependenciesServer) error
	GetTopology(*Request, DependencyTrackingService_GetTopologyServer) error
	GetTopologyTiered(*Request, DependencyTrackingService_GetTopologyTieredServer) error
	GetSources(*GetSourcesRequest, DependencyTrackingService_GetSourcesServer) error
	ListLanguages(context.Context, *ListLanguagesRequest) (*ListLanguagesResponse, error)
	ListOrganizations(context.Context, *ListOrganizationsRequest) (*ListOrganizationsResponse, error)
	ListModules(context.Context, *ListModulesRequest) (*ListModulesResponse, error)
}

func RegisterDependencyTrackingServiceServer(s *grpc.Server, srv DependencyTrackingServiceServer) {
	s.RegisterService(&_DependencyTrackingService_serviceDesc, srv)
}

func _DependencyTrackingService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyTrackingServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.rds.api.DependencyTrackingService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyTrackingServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DependencyTrackingService_GetDependencies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DependencyTrackingServiceServer).GetDependencies(m, &dependencyTrackingServiceGetDependenciesServer{stream})
}

type DependencyTrackingService_GetDependenciesServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type dependencyTrackingServiceGetDependenciesServer struct {
	grpc.ServerStream
}

func (x *dependencyTrackingServiceGetDependenciesServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _DependencyTrackingService_GetTopology_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DependencyTrackingServiceServer).GetTopology(m, &dependencyTrackingServiceGetTopologyServer{stream})
}

type DependencyTrackingService_GetTopologyServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type dependencyTrackingServiceGetTopologyServer struct {
	grpc.ServerStream
}

func (x *dependencyTrackingServiceGetTopologyServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _DependencyTrackingService_GetTopologyTiered_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DependencyTrackingServiceServer).GetTopologyTiered(m, &dependencyTrackingServiceGetTopologyTieredServer{stream})
}

type DependencyTrackingService_GetTopologyTieredServer interface {
	Send(*TieredResponse) error
	grpc.ServerStream
}

type dependencyTrackingServiceGetTopologyTieredServer struct {
	grpc.ServerStream
}

func (x *dependencyTrackingServiceGetTopologyTieredServer) Send(m *TieredResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DependencyTrackingService_GetSources_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSourcesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DependencyTrackingServiceServer).GetSources(m, &dependencyTrackingServiceGetSourcesServer{stream})
}

type DependencyTrackingService_GetSourcesServer interface {
	Send(*GetSourcesResponse) error
	grpc.ServerStream
}

type dependencyTrackingServiceGetSourcesServer struct {
	grpc.ServerStream
}

func (x *dependencyTrackingServiceGetSourcesServer) Send(m *GetSourcesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DependencyTrackingService_ListLanguages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLanguagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyTrackingServiceServer).ListLanguages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.rds.api.DependencyTrackingService/ListLanguages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyTrackingServiceServer).ListLanguages(ctx, req.(*ListLanguagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DependencyTrackingService_ListOrganizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrganizationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyTrackingServiceServer).ListOrganizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.rds.api.DependencyTrackingService/ListOrganizations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyTrackingServiceServer).ListOrganizations(ctx, req.(*ListOrganizationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DependencyTrackingService_ListModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyTrackingServiceServer).ListModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.deps.rds.api.DependencyTrackingService/ListModules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyTrackingServiceServer).ListModules(ctx, req.(*ListModulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DependencyTrackingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.deps.rds.api.DependencyTrackingService",
	HandlerType: (*DependencyTrackingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "put",
			Handler:    _DependencyTrackingService_Put_Handler,
		},
		{
			MethodName: "listLanguages",
			Handler:    _DependencyTrackingService_ListLanguages_Handler,
		},
		{
			MethodName: "listOrganizations",
			Handler:    _DependencyTrackingService_ListOrganizations_Handler,
		},
		{
			MethodName: "listModules",
			Handler:    _DependencyTrackingService_ListModules_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getDependencies",
			Handler:       _DependencyTrackingService_GetDependencies_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "getTopology",
			Handler:       _DependencyTrackingService_GetTopology_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "getTopologyTiered",
			Handler:       _DependencyTrackingService_GetTopologyTiered_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "getSources",
			Handler:       _DependencyTrackingService_GetSources_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dts.proto",
}

func init() { proto.RegisterFile("dts.proto", fileDescriptor_dts_4e337ae99d5cade8) }

var fileDescriptor_dts_4e337ae99d5cade8 = []byte{
	// 716 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x6b, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0xeb, 0xda, 0xad, 0xb7, 0x7b, 0xd5, 0xc0, 0xd4, 0x85, 0x01, 0x95, 0xc5, 0x46, 0x87,
	0xb6, 0x6c, 0x2a, 0x8f, 0x2f, 0x13, 0x12, 0xa0, 0x31, 0xb4, 0x69, 0x2f, 0xa5, 0x65, 0x48, 0x48,
	0x43, 0xca, 0x62, 0x13, 0xac, 0x25, 0x71, 0x88, 0x1d, 0xa4, 0xf1, 0xc3, 0x90, 0xf8, 0x53, 0xfc,
	0x06, 0x54, 0xe7, 0xd1, 0xb4, 0xcd, 0xb6, 0xc2, 0xbe, 0xe5, 0xda, 0xf7, 0x1c, 0xdf, 0x7b, 0x7c,
	0x8f, 0x15, 0xa8, 0x12, 0x29, 0x8c, 0x20, 0xe4, 0x92, 0x23, 0x64, 0xbb, 0x3c, 0x22, 0x06, 0xa1,
	0x81, 0x30, 0x42, 0x22, 0x0c, 0x2b, 0x60, 0x7a, 0xcb, 0x61, 0xf2, 0x5b, 0x74, 0x6e, 0xd8, 0xdc,
	0xdb, 0xec, 0x6d, 0x6c, 0xa8, 0x9c, 0x4d, 0x42, 0xc5, 0xa6, 0x15, 0x30, 0xb5, 0x14, 0xa3, 0xf1,
	0x0a, 0xd4, 0x3b, 0x3c, 0x0a, 0x6d, 0xba, 0xe7, 0x7f, 0xe5, 0xa1, 0x67, 0x49, 0xc6, 0x7d, 0xb4,
	0x00, 0xa5, 0x28, 0x74, 0x1b, 0x13, 0x4d, 0xad, 0x55, 0x35, 0x7b, 0x9f, 0x78, 0x1f, 0x66, 0x76,
	0x68, 0x40, 0x7d, 0x42, 0x7d, 0xfb, 0x72, 0x8f, 0x20, 0x0c, 0x33, 0x3c, 0x74, 0x2c, 0x9f, 0xfd,
	0x54, 0x88, 0x86, 0xa6, 0x52, 0x07, 0xd6, 0xd0, 0x22, 0x54, 0x3c, 0x4e, 0x22, 0x97, 0x26, 0x44,
	0x49, 0x84, 0x7f, 0x6b, 0x00, 0x27, 0x91, 0x34, 0xe9, 0xf7, 0x88, 0x0a, 0x89, 0x3a, 0x50, 0x17,
	0xc3, 0x15, 0x28, 0xbe, 0x5a, 0x7b, 0xc5, 0x18, 0xed, 0xcd, 0x18, 0x29, 0xd7, 0x1c, 0xc5, 0xa3,
	0x53, 0x98, 0xf7, 0x2c, 0xdf, 0x72, 0xa8, 0x47, 0x7d, 0xb9, 0xcb, 0x5c, 0x2a, 0x1a, 0x13, 0xcd,
	0x52, 0xab, 0xd6, 0x5e, 0xcf, 0x53, 0x12, 0x1a, 0x53, 0xf6, 0x5b, 0x3b, 0x1c, 0x00, 0x99, 0xc3,
	0x24, 0x78, 0x1b, 0x6a, 0xaa, 0x74, 0x11, 0x70, 0x5f, 0x50, 0x84, 0x60, 0xd2, 0xe6, 0x84, 0xaa,
	0x72, 0xcb, 0xa6, 0xfa, 0x46, 0x0d, 0x98, 0xf2, 0xa8, 0x10, 0x96, 0x93, 0xf6, 0x9d, 0x86, 0xf8,
	0x97, 0x06, 0x53, 0x69, 0xd7, 0x3a, 0x4c, 0xbb, 0x96, 0xef, 0x44, 0xbd, 0xb4, 0x58, 0xbc, 0x2c,
	0xee, 0x09, 0x27, 0x2e, 0x85, 0xa4, 0x5e, 0x2a, 0x5c, 0x1c, 0x8d, 0x88, 0x5e, 0xbe, 0x56, 0xf4,
	0x4a, 0x5e, 0x74, 0xb4, 0x0d, 0x55, 0xc2, 0x42, 0x6a, 0x2b, 0xe0, 0x54, 0x53, 0x6b, 0xcd, 0xb5,
	0x1f, 0x16, 0xa9, 0xbb, 0x93, 0x26, 0x99, 0xfd, 0x7c, 0x7c, 0x00, 0xd3, 0x59, 0xcb, 0x6f, 0x00,
	0x48, 0x26, 0x57, 0x72, 0x4f, 0xcd, 0x42, 0xa6, 0xdc, 0xbc, 0x98, 0x39, 0x0c, 0xde, 0x85, 0xb9,
	0x2e, 0xa3, 0x21, 0x25, 0x19, 0xe7, 0x0b, 0x98, 0x94, 0x8c, 0x86, 0x0d, 0x4d, 0x5d, 0xd1, 0xcd,
	0x6c, 0x2a, 0x1b, 0x5f, 0x40, 0xfd, 0x03, 0x95, 0xf1, 0x38, 0x88, 0x71, 0x74, 0xbd, 0x85, 0x7e,
	0xb8, 0x03, 0x28, 0x7f, 0x58, 0x52, 0xf8, 0x6b, 0xa8, 0xc4, 0xb3, 0xf7, 0x6f, 0x03, 0x9b, 0x80,
	0xf0, 0x22, 0xdc, 0x3b, 0x60, 0x42, 0x1e, 0x24, 0x05, 0xa6, 0x4d, 0xe0, 0x97, 0x70, 0x7f, 0x68,
	0x3d, 0x39, 0x6f, 0x19, 0xaa, 0x69, 0x37, 0x42, 0xa9, 0x55, 0x35, 0xfb, 0x0b, 0xf8, 0x15, 0x34,
	0x7a, 0xb0, 0xe3, 0x5c, 0x3f, 0xe3, 0xe8, 0x82, 0xcf, 0x60, 0xa9, 0x00, 0x97, 0x1c, 0x79, 0x9d,
	0xa0, 0x4f, 0x60, 0x36, 0x2f, 0x5e, 0xec, 0xb1, 0xaa, 0x39, 0xb8, 0x88, 0xbb, 0x80, 0x7a, 0xf4,
	0x87, 0x4a, 0xc8, 0xff, 0xba, 0xa8, 0x89, 0xd1, 0x8b, 0xc2, 0x1c, 0xee, 0x0e, 0xb0, 0x8e, 0x51,
	0xee, 0x18, 0xb4, 0xca, 0xbd, 0x31, 0x65, 0xa3, 0xa4, 0x9a, 0x49, 0xc3, 0x67, 0x6b, 0x50, 0xcd,
	0xcc, 0x81, 0x66, 0x60, 0xfa, 0xe3, 0x49, 0xa7, 0x6b, 0xbe, 0x7f, 0x7b, 0xb8, 0x70, 0x07, 0xcd,
	0x01, 0xec, 0x1c, 0x7f, 0x3a, 0x4a, 0x62, 0xad, 0xfd, 0xa7, 0x0c, 0x4b, 0xfd, 0x81, 0xed, 0x86,
	0x96, 0x7d, 0xc1, 0x7c, 0xa7, 0x43, 0xc3, 0x1f, 0xcc, 0xa6, 0x68, 0x17, 0x4a, 0x41, 0x24, 0xd1,
	0xa3, 0xa2, 0x59, 0xe9, 0xbf, 0x8b, 0xfa, 0xe3, 0x2b, 0xf7, 0x93, 0x56, 0x8f, 0x60, 0xde, 0xa1,
	0x32, 0x3b, 0x87, 0x51, 0x81, 0x1e, 0x14, 0x61, 0x52, 0xc2, 0xe5, 0xe2, 0xcd, 0x98, 0x6d, 0x4b,
	0x43, 0xfb, 0x50, 0x73, 0xa8, 0xec, 0xf2, 0x80, 0xbb, 0xdc, 0xb9, 0xbc, 0x1d, 0xd7, 0x29, 0xd4,
	0x73, 0x5c, 0xb1, 0xdd, 0xaf, 0x67, 0xc4, 0x45, 0x9b, 0x83, 0xef, 0xc4, 0x96, 0x86, 0xce, 0x00,
	0x9c, 0xcc, 0x86, 0xa8, 0xd0, 0x6e, 0x23, 0x6f, 0x82, 0xbe, 0x7a, 0x53, 0x5a, 0x46, 0x4f, 0x60,
	0xd6, 0xcd, 0x1b, 0x0f, 0xb5, 0x8a, 0xa0, 0x45, 0x9e, 0xd5, 0xd7, 0xc6, 0xc8, 0x4c, 0x2e, 0x2e,
	0x80, 0xba, 0x3b, 0xec, 0x37, 0xb4, 0x7e, 0x15, 0xbe, 0xc8, 0xce, 0xfa, 0xc6, 0x98, 0xd9, 0xc9,
	0x89, 0x5f, 0xa0, 0xe6, 0xf6, 0xcd, 0x82, 0x56, 0xaf, 0x42, 0x0f, 0x7a, 0x54, 0x7f, 0x7a, 0x63,
	0x5e, 0xcc, 0xff, 0xae, 0xfc, 0xb9, 0x64, 0x05, 0xec, 0xbc, 0xa2, 0xfe, 0x29, 0x9e, 0xff, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0xef, 0x93, 0x68, 0x17, 0x9e, 0x08, 0x00, 0x00,
}
